### ISSUE TITLE
Versions aren't showing after complex syntax

### ISSUE THREAD

**Issue by Kwelity** [meain/vim-package-info#10]
Using the plugin with rust in a Toml file, the version numbers stop showing if a plugins requires a special feature (i.e. if the syntax differs from key / value.

![Screenshot from 2019-04-19 08-46-26](https://user-images.githubusercontent.com/2639732/56411391-daefdf00-6280-11e9-8198-c0edb4e5a741.png)

**Comment by meain** [comment]
Should be fixed with https://github.com/meain/vim-package-info/pull/11

**Comment by Kwelity** [comment]
It does, thanks !

**Comment by meain** [comment]
Awesome.
