### ISSUE TITLE
ALE issues

### ISSUE THREAD

**Issue by Mange** [meain/vim-package-info#14]
**NOTE:** I'm not saying that you can do anything about this, but perhaps this would be useful to show as a disclaimer in the README or something.

---

When moving the cursor in the package file all version texts disappear. Entering insert mode and leaving it again will show the text but then moving the cursor again will hide the text just like before.

This seems to happen because of ALE, and `:ALEDisable` removes the weird behavior. I suspect this is because ALE tries to run all linters and since it can't find anything wrong on the lines, it clears the text.

~I'm going to see about making ALE only evaluate when leaving insert mode anyway, so I probably won't have this issue for longer.~ I already had that so the issue was something else.

[EDIT]: The issue is caused by `g:ale_virtualtext_cursor` not being set to `0`, which makes ALE try to hide virtualtext that isn't close to the cursor. It will hide all virtualtext in the buffer when you move the cursor.

Just wanted to bring it up in case someone else is wondering about this.

Cool project, btw! Thanks!

**Comment by meain** [comment]
Oh yeah, I had forgotten about this since I had ale errors and warning always just show up on the bottom for me.

Thanks for taking time to mention this here. I will add some general warning for this clashing with other plugins that use `virtualtext` in the README.

Glad you found the project useful.

**Comment by meain** [comment]
I have added some info in the readme about this.
