### ISSUE TITLE
Install instructions not complete or npm problem

### ISSUE THREAD

**Issue by alerque** [meain/vim-package-info#20]
I can't get this plugin to work, and I'm not sure if the issue is my not knowing where to run what, or if npm isn't working right. Either way I'm unable to get it to work.

* Neovim
* Vim-Plug, config copied from Readme, ran `:PlugInstall`
* `.config/nvim/plugged/vim-package-info/node_modules/...` seem to be present

Running `:UpdateRemotePlugins` gives this error:

```
function remote#host#UpdateRemotePlugins[6]..<SNR>90_RegistrationCommands[15]..remote#host#Require[10]..provider#node#Require, line 2          
Vim(echoerr):Cannot find the "neovim" node package. Try :checkhealth
```

Running it a second time in a session says it's already registered, but in neither case does the plugin actually function. Opening a `package.json` file shows no virtual text.

**Comment by meain** [comment]
You will have to run `npm install -g neovim` so that neovim has support for node based plugins.

Once this is installed, you can do `:checkhealth` inside neovim and you should get something like this in the result.

![](https://i.imgur.com/2rc6XC9.png)

Once that is done, just do `:UpdateRemotePlugins` again and you should be good to go.

**Comment by alerque** [comment]
Oh I see. Given that I solved this by installing my distro's `nodejs-neovim` package (just a system package wrapper for the npm package). It does in fact work now...thanks for the help.

However that `npm install -g neovim` bit should be part of the main README file so other people don't miss the step.

**Comment by meain** [comment]
Yeah, I think it is better to add in readme. I will add it in.

 I am closing the issue as you have got it working.
