### ISSUE TITLE
Possible improvements

### ISSUE THREAD

**Issue by Psykopear** [meain/vim-package-info#23]
Hi! I really like this package and find it very useful.

I installed it some time ago, then it stopped working (obviously it's in its early life), and since I'm studying Rust, I tried to reimplement it.

I found some things that could be improved in this package's implementation.
I'm not going to contribute with code, but I wanted to share what I learned with you

- The `range` in the manifest file (package.json, Pipfile...) should be treated as such, rather than as a `version`. You could use [semver on npm](https://www.npmjs.com/package/semver) to parse the string and use it to check against the actual version:`semver.satisfies('1.2.3', '1.x || >=2.5.0 || 5.0.0 - 7.2.3') // true`

- If you parse the generated lockfile (it's toml for both python and rust, and there is a library made by the yarn developers to parse yarn.lock that's in a custom format) you can have the exact version that should be installed in the environment, so no need to manually remove characters from the string

- Once you have both the requirement and the actual version, you could  always show the current version and only show the latest if it's different, like
![image](https://user-images.githubusercontent.com/5968682/57326864-b9f70d00-710d-11e9-85df-e927b66f1998.png)

- Make async requests to the stores, it really speeds things up and it shouldn't be problematic to do in js

**Comment by meain** [comment]
Hey, thanks a lot for taking time to comment in here. All of them seem to be valid points and I will try to add them in.

Btw, if you are having issues with the plugin just do a `:UpdateRemotePlugins`.
It stops working when we add a new autocommand. But just running `:UpdateRemotePlugins` should solve the problem.
