### ISSUE TITLE
Feature request: Show package size

### ISSUE THREAD

**Issue by perrupa** [meain/vim-package-info#6]
It would be handy for front end developers to have a general sense of the package size they're incurring if it were a client-side deliverable. 

Possible features/options:
- total package size
- gzipped size
- bundled size (just the skipped code, no tests, docs, etc)
- taking tree shaking into account

I'm going to take a look at the code and try to get a sense of how crazy those'd be to do and if I'm capable of lending a hand 😅

**Comment by meain** [comment]
I have a feeling that it might be a bit hard to get the size with tree shaking info and stuff. Without all that info, the size might not be all that useful at times.
I also think that a lot of other config files might have a some features like tree shaking.

It is just that it might be a bit of work to support size at the moment and I don't want to get into it right now.

Besides there are plugins like [vim-import-cost](https://github.com/yardnsm/vim-import-cost) which already does the size computation part much better.

**Comment by perrupa** [comment]
Right on, if it's not the goal of this project it makes sense to close this idea.

Cheers 👌
