### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by KillTheMule** [meain/vim-package-info#8]
The highlight groups in the README don't exist for me, the only highlight groups I could see that would be related are VimPackageJsonPatch and VimPackageJsonMinor. Also, the color does not change when I change the version strings, I have to reload the file. Tried it on a Cargo.toml, if you want details let me know what I should provide.

**Comment by meain** [comment]
I have fixed the highlight group issue, it was some stuff that I forgot to change after the name change.

Also it was just redrawing it only on `InsertLeave`. I have added `TextChange`. So now you should be able to see the changes instantly.

**Comment by KillTheMule** [comment]
Ok, that works now, thanks :) An additional suggestion would be not to hardcode the colros, but to link the groups to some default groups, since the probability would be higher that this works sanely for different color schemes.

**Comment by meain** [comment]
I thought about that but I think the semantic meaning of `red`, `cyan` and `green` is a bit important.
If we were to just link to a default highlight group we may not be able to guarantee that as themes at times go nuts with colors or there are ones that even lack a good number of colors like redblack for example.

**Comment by KillTheMule** [comment]
That's true, except that it doesn't show up properly on all terminals. E.g. my terminal does not support truecolor, and I only get variations of grey showing up. I can of course override the HL groups, but I wonder how many people might have this problem... maybe not many but the users of solarized (which means people overridde the standard terminal colors). I guess it's good this way, I'll just override the settings locally :+1:

**Comment by meain** [comment]
What do you override it to? I have a feeling that I might not be setting `ctermfg` correctly.

If you are linking it to something, could you please send me what it is using.

**Comment by KillTheMule** [comment]
People who use solarized in a non-truecolor terminal change the standard color via Xresources, see https://github.com/altercation/solarized/blob/master/xresources/solarized. I don't think there's anything you can do if you don't want to link to standard groups.

**Comment by meain** [comment]
I am setting something like this
```vim
highlight default VimPackageInfoPatch guifg=#8BC34A ctermfg=10
```

I am guessing you have mapped 10 to some shade of grey with your terminal colors, right?

**Comment by KillTheMule** [comment]
Yep, it's the default text color, grey.

**Comment by KillTheMule** [comment]
Hmm, that said, what's the default color? I could not find out where or if you set it, but it turns up bold for me, and I'd like to change that. Do you set it, or do I need to try to dig out the default for virtualtext?

**Comment by meain** [comment]
https://github.com/meain/vim-package-info/blob/master/plugin/vim-package-info.vim

This is where I have set it
